<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/capture-spaceless.latte */
final class LatteTpl_fixtures_capture_spaceless_latte_520212b0 extends \Latte\Runtime\Template
{
    public const Source = 'fixtures/capture-spaceless.latte';
    /**
     * @param string $x
     */
    public function latteMain($x): void
    {
        echo "\n";
        echo '	captured ';
        echo $x;
        echo "\n";
        $v = \OriPhpstan\Nette\Latte\Runtime\Helpers::capturedString();
        echo "\n";
        echo '	<div>
		<span>';
        echo $x;
        echo '</span>
	</div>
';
        echo '
{literal brace}

';
        \OriPhpstan\Nette\Latte\Runtime\Helpers::analyzed($x, '$x');
    }
}