<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/filtered-block.latte */
final class LatteTpl_fixtures_filtered_block_latte_7f2fe8d9 extends \Latte\Runtime\Template
{
    public const Source = 'fixtures/filtered-block.latte';
    public function latteMain(): void
    {
        if ($this->hasBlock('title')) {
            \ob_start(fn() => '');
            try {
                $this->renderBlock('title', [], 'html');
            } finally {
                echo \Latte\Runtime\Filters::convertTo(\OriPhpstan\Nette\Latte\Runtime\Helpers::filterInfo(), 'html', \Latte\Essential\Filters::trim(\OriPhpstan\Nette\Latte\Runtime\Helpers::filterInfo(), \Latte\Essential\Filters::stripTags(\OriPhpstan\Nette\Latte\Runtime\Helpers::filterInfo(), \ob_get_clean())));
            }
        }
    }
}