<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/foreach-iterator.latte */
final class LatteTpl_fixtures_foreach_iterator_latte_898f2db1 extends \Latte\Runtime\Template
{
    public const Source = 'fixtures/foreach-iterator.latte';
    /**
     * @param array $items
     * @param array $groups
     */
    public function latteMain($items, $groups): void
    {
        echo "\n";
        foreach ($items as $item) {
            echo '	';
            echo $item;
            echo "\n";
        }
        echo "\n";
        $iterator = new \Latte\Essential\CachingIterator($items);
        foreach ($items as $key => $item) {
            echo '	';
            if ($iterator->isFirst()) {
                echo 'first ';
            }
            echo $item;
            if ($iterator->isLast()) {
                echo ' last';
            }
            echo "\n";
        }
        echo "\n";
        $iterator = new \Latte\Essential\CachingIterator($groups);
        foreach ($groups as $group) {
            $iterator = new \Latte\Essential\CachingIterator($group);
            foreach ($group as $item) {
                echo '		';
                if ($iterator->isFirst()) {
                    echo 'head ';
                }
                echo $item;
                if ($iterator->isLast()) {
                    echo ' tail';
                }
                echo "\n";
            }
        }
        echo "\n";
        $iterator = new \Latte\Essential\CachingIterator($items);
        foreach ($items as $item) {
            do {
                echo '		';
                echo $item;
                echo "\n";
                if (!$iterator->hasNext() || !($item === $item)) {
                    break;
                }
                $iterator->next();
                [, $item] = [$iterator->key(), $iterator->current()];
            } while (\true);
            echo '	';
            if (!$iterator->isLast()) {
                echo ', ';
            }
            echo "\n";
        }
    }
}