<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/forms-macros.latte */
final class LatteTpl_fixtures_forms_macros_latte_257f81ab extends \Latte\Runtime\Template
{
    public const Source = 'fixtures/forms-macros.latte';
    public function latteMain(): void
    {
        $form = \OriPhpstan\Nette\Latte\Runtime\Helpers::form('f');
        echo '<form';
        echo '>
	<input';
        echo ($latteElem = \OriPhpstan\Nette\Latte\Runtime\Helpers::formField('x')->getControlPart())->attributes();
        echo '>
	';
        echo $latteLabel = \OriPhpstan\Nette\Latte\Runtime\Helpers::formField('x')->getLabel();
        echo '
	';
        echo \OriPhpstan\Nette\Latte\Runtime\Helpers::formField('x')->getError();
        echo "\n";
        echo '</form>
';
        echo "\n";
        $form = \OriPhpstan\Nette\Latte\Runtime\Helpers::form('f2');
        echo '
	';
        echo \OriPhpstan\Nette\Latte\Runtime\Helpers::formField('y')->getControl();
        echo "\n";
        $formContainer = \OriPhpstan\Nette\Latte\Runtime\Helpers::formContainer('c');
        echo '		';
        echo \OriPhpstan\Nette\Latte\Runtime\Helpers::formField('z')->getControl();
        echo "\n";
        echo "\n";
    }
}