<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/ifcurrent.latte */
final class LatteTpl_fixtures_ifcurrent_latte_90517d0b extends \Latte\Runtime\Template
{
    public const Source = 'fixtures/ifcurrent.latte';
    /**
     * @param string $dest
     * @param string $label
     */
    public function latteMain($dest, $label): void
    {
        echo "\n";
        \OriPhpstan\Nette\Latte\Runtime\Helpers::analyzed('x');
        if (\OriPhpstan\Nette\Latte\Runtime\Helpers::uiIsLinkCurrent($dest)) {
            echo '	';
            echo $label;
            echo "\n";
        }
        echo "\n";
        if (\OriPhpstan\Nette\Latte\Runtime\Helpers::uiIsLinkCurrent(null)) {
            echo '	';
            echo $label;
            echo "\n";
        }
    }
}