<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/n-attributes.latte */
final class LatteTpl_fixtures_n_attributes_latte_366f42ea extends \Latte\Runtime\Template
{
    public const Source = 'fixtures/n-attributes.latte';
    /**
     * @param bool $cond
     * @param array $items
     * @param string $activeClass
     * @param string $tagName
     */
    public function latteMain($cond, $items, $activeClass, $tagName): void
    {
        echo "\n";
        if ($cond) {
            echo '<div>shown</div>
';
        }
        echo '
<ul>
';
        foreach ($items as $item) {
            echo '	<li>';
            echo $item;
            echo '</li>
';
        }
        echo '</ul>

<div>';
        foreach ($items as $item) {
            echo $item;
        }
        echo '</div>

';
        $latteTag0 = '';
        if ($cond) {
            $latteTag0 = '</div>' . $latteTag0;
            echo '<div>';
        }
        echo 'tag-if content';
        echo $latteTag0;
        echo '

<div';
        echo \OriPhpstan\Nette\Latte\Runtime\Helpers::classes([$cond ? 'active' : \null, $activeClass, 'base']);
        echo '>class</div>

<div';
        echo \OriPhpstan\Nette\Latte\Runtime\Helpers::classes([$cond ? 'form-group has-error' : 'form-group']);
        echo '>always-truthy class</div>

<div';
        echo \Latte\Essential\Nodes\NAttrNode::attrs(['data-x' => $cond ? 1 : \null], \false);
        echo '></div>

';
        $latteTag1 = '';
        $latteTagName = \Latte\Runtime\HtmlHelpers::validateTagChange($tagName, 'div');
        $latteTag1 = '</' . $latteTagName . '>' . $latteTag1;
        echo '<', $latteTagName;
        echo '>tag';
        echo $latteTag1;
        echo '

';
        echo '<p>';
        if ($cond) {
            echo 'x';
        }
        echo '</p>
';
        echo '
<script';
        echo '>window.x=1;</script>
';
    }
}