<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/parameters.latte */
final class LatteTpl_fixtures_parameters_latte_031c1534 extends \Latte\Runtime\Template
{
    public const Source = 'fixtures/parameters.latte';
    /**
     * @param string $name
     * @param int $age
     */
    public function latteMain($name, $age = 18): void
    {
        echo '
Hello ';
        echo $name;
        echo ', age ';
        echo $age;
        echo "\n";
    }
}