<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/probes.latte */
final class LatteTpl_fixtures_probes_latte_4c7d2b2d extends \Latte\Runtime\Template
{
    public const Source = 'fixtures/probes.latte';
    public const Blocks = [['wrapper' => 'blockWrapper']];
    /**
     * @param string $name
     * @param string $mode
     */
    public function latteMain($name, $mode): void
    {
        $this->createTemplate('blocks-snippets.latte', $this->params, "import")->render();
        echo "\n";
        $this->addBlock($ʟ_nm = $name, 'html', [[$this, 'blockName']], 0);
        $this->renderBlock($ʟ_nm, []);
        echo '

';
        $this->blockWrapper($name, $mode);
        echo "\n";
        \ob_start(fn() => '');
        try {
            echo 'anonymous filtered ';
            echo $mode;
        } finally {
            echo \Latte\Runtime\Filters::convertTo(\OriPhpstan\Nette\Latte\Runtime\Helpers::filterInfo(), 'html', \Latte\Essential\Filters::upper(\ob_get_clean()));
        }
        echo '

';
        \ob_start(fn() => '');
        try {
            $this->createTemplate('declarations.latte', ['flag' => \true], 'sandbox')->renderToContentType('html');
        } catch (\Throwable $latteException) {
            if (isset($this->global->coreExceptionHandler)) {
                \ob_clean();
                ($this->global->coreExceptionHandler)($latteException, $this);
            } else {
                throw $latteException;
            }
        } finally {
            echo \ob_get_clean();
        }
        echo "\n";
    }
    /**
     * @param string $name
     * @param string $mode
     */
    public function blockName($name, $mode): void
    {
        echo 'dynamic ';
        echo $name;
    }
    /**
     * @param string $name
     * @param string $mode
     */
    public function blockWrapper($name, $mode): void
    {
        $this->renderParentBlock('wrapper', []);
    }
}