<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/ui-macros.latte */
final class LatteTpl_fixtures_ui_macros_latte_1e9a68ee extends \Latte\Runtime\Template
{
    public const Source = 'fixtures/ui-macros.latte';
    /**
     * @param object $obj
     */
    public function latteMain($obj): void
    {
        echo "\n";
        \OriPhpstan\Nette\Latte\Runtime\Helpers::component('menu');
        echo "\n";
        \OriPhpstan\Nette\Latte\Runtime\Helpers::component($obj);
        [1, 'a' => 2];
        echo '
<a href="';
        echo \OriPhpstan\Nette\Latte\Runtime\Helpers::uiLink('this');
        echo '">this</a>

<a href="';
        echo \OriPhpstan\Nette\Latte\Runtime\Helpers::uiLink('Foo:bar');
        echo '">bar</a>

<a href="';
        echo \OriPhpstan\Nette\Latte\Runtime\Helpers::uiLink('Foo:baz', [1, 'x' => 2]);
        echo '">baz</a>
';
    }
}