<?php declare(strict_types = 1);

namespace Tests\OriPhpstan\Nette\Integration\Latte\Rule;

use Nette\Neon\Neon;
use Nette\Utils\FileSystem;
use OriPhpstan\Nette\Latte\Rule\LatteProvenanceTipRule;
use PhpParser\Node;
use PHPStan\Rules\Rule;
use PHPStan\Testing\RuleTestCase;
use Tests\OriPhpstan\Nette\Integration\Latte\Rule\Fixtures\ForbiddenCallFixtureRule;
use Tests\OriPhpstan\Nette\Toolkit\PipelineFactory;
use function sys_get_temp_dir;

// Real pipeline, end to end: {_'Hello'} compiles through the REAL vendor
// gettext macro set (h4kuna\Gettext\Macros\Gettext, same fixture engine loader
// HarvestedGettextMacroIntegrationTest uses) into a genuine gettext() call - the shipmonk denial
// this app's own gettext migration backlog is built on. The macro tag never survives into the
// generated code, so the tip is the only thing naming its origin.
/**
 * @extends RuleTestCase<LatteProvenanceTipRule<Node>>
 */
final class LatteProvenanceTipGettextIntegrationTest extends RuleTestCase
{

	private const FixtureFile = __DIR__ . '/../../../Unit/Latte/Fixtures/Rule/provenance-tip-gettext.latte';

	/**
	 * @return LatteProvenanceTipRule<Node>
	 */
	protected function getRule(): Rule
	{
		return new LatteProvenanceTipRule(
			new ForbiddenCallFixtureRule(['gettext' => 'Use t() instead.']),
			PipelineFactory::createTemplateEdgeIndex(__DIR__ . '/../../../Unit/Latte/Fixtures/Rule'),
		);
	}

	/**
	 * @return list<string>
	 */
	public static function getAdditionalConfigFiles(): array
	{
		return [self::generatedConfigPath()];
	}

	public function testGettextMacroGeneratedDenialGetsAMacroProvenanceTip(): void
	{
		$this->analyse(
			[self::FixtureFile],
			[
				[
					'Function gettext() is forbidden. Use t() instead.',
					1,
					'Generated by the {_} macro at column 1.',
				],
			],
		);
	}

	// Written once per process into a fixed scratch path (not per-call __DIR__-relative neon,
	// which would need orisaiNette.latte.engineLoader resolved against an unpredictable CWD under RuleTestCase
	// - see config/latte.neon's currentWorkingDirectory-rooted defaults) - every path embedded is absolute,
	// so the generated file's own location never matters.
	private static function generatedConfigPath(): string
	{
		$path = sys_get_temp_dir() . '/latte-provenance-tip-gettext-test.neon';
		FileSystem::write(
			$path,
			Neon::encode(
				[
					'parameters' => [
						'customRulesetUsed' => true,
						'bootstrapFiles' => [__DIR__ . '/../../../../vendor/autoload.php'],
						'fileExtensions' => ['php', 'latte'],
						'orisaiNette' => [
							'latte' => [
								'enabled' => true,
								'engineLoader' => __DIR__ . '/../../../Unit/Latte/Customs/Fixtures/engine-loader-gettext.php',
							],
						],
					],
					'includes' => [__DIR__ . '/../../../../extension.neon'],
				],
				true,
			),
		);

		return $path;
	}

}
