<?php declare(strict_types = 1);

namespace Tests\OriPhpstan\Nette\Integration\Latte\Rule;

use OriPhpstan\Nette\Latte\Rule\LatteProvenanceTipRule;
use PhpParser\Node;
use PHPStan\Rules\Rule;
use PHPStan\Testing\RuleTestCase;
use Tests\OriPhpstan\Nette\Integration\Latte\Rule\Fixtures\ForbiddenCallFixtureRule;
use Tests\OriPhpstan\Nette\Toolkit\PipelineFactory;
use Tests\OriPhpstan\Nette\Toolkit\VersionGroupGate;

// Real pipeline, end to end: {$x|webalize} compiles through
// FilterRewriter into a real Nette\Utils\Strings::webalize() static call - the node FilterRewriter
// itself tags with the provenance attribute, proving the attribute survives from the rewriter
// into the exact node the rule dispatch (and therefore this decorator) sees.
/**
 * @extends RuleTestCase<LatteProvenanceTipRule<Node>>
 *
 * @group latte2
 */
final class LatteProvenanceTipFilterIntegrationTest extends RuleTestCase
{

	use VersionGroupGate;

	private const FixtureFile = __DIR__ . '/../../../Unit/Latte/Fixtures/Rule/provenance-tip-filter.latte';

	/**
	 * @return LatteProvenanceTipRule<Node>
	 */
	protected function getRule(): Rule
	{
		return new LatteProvenanceTipRule(
			new ForbiddenCallFixtureRule(['Nette\Utils\Strings::webalize' => 'test denial']),
			PipelineFactory::createTemplateEdgeIndex(__DIR__ . '/../../../Unit/Latte/Fixtures/Rule'),
		);
	}

	/**
	 * @return list<string>
	 */
	public static function getAdditionalConfigFiles(): array
	{
		return [__DIR__ . '/../../../Unit/Latte/Rule/phpstan-test-provenance-tip-filter.neon'];
	}

	public function testFilterRewrittenNodeDenialGetsAFilterProvenanceTip(): void
	{
		$this->analyse(
			[self::FixtureFile],
			[
				[
					'Method Nette\Utils\Strings::webalize() is forbidden. test denial',
					1,
					'Generated by the |webalize filter.',
				],
			],
		);
	}

}
