<?php declare(strict_types = 1);

namespace Tests\OriPhpstan\Nette\Integration\Latte\Rule;

use OriPhpstan\Nette\Latte\Rule\LatteProvenanceTipRule;
use PhpParser\Node;
use PHPStan\Rules\Rule;
use PHPStan\Testing\RuleTestCase;
use Tests\OriPhpstan\Nette\Integration\Latte\Rule\Fixtures\FunctionVsMacroLineFixtureRule;
use Tests\OriPhpstan\Nette\Toolkit\PipelineFactory;

// Pinned together at the rule level through the
// real pipeline: {foreach $xs as $x}{clamp($x, 0, 10)}{if true}{/if}{/foreach} - one source line
// carrying two macro tags (foreach, if) AND a harvested-function call (clamp, real global
// FunctionTable entry, compiles through FilterRewriter's $this->global->fn->clamp(...) shape).
/**
 * @extends RuleTestCase<LatteProvenanceTipRule<Node>>
 */
final class LatteProvenanceTipFunctionVsMacroLineIntegrationTest extends RuleTestCase
{

	private const FixtureFile = __DIR__ . '/../../../Unit/Latte/Fixtures/Rule/provenance-tip-function-vs-macro-line.latte';

	/**
	 * @return LatteProvenanceTipRule<Node>
	 */
	protected function getRule(): Rule
	{
		return new LatteProvenanceTipRule(
			new FunctionVsMacroLineFixtureRule(),
			PipelineFactory::createTemplateEdgeIndex(__DIR__ . '/../../../Unit/Latte/Fixtures/Rule'),
		);
	}

	/**
	 * @return list<string>
	 */
	public static function getAdditionalConfigFiles(): array
	{
		return [__DIR__ . '/../../../Unit/Latte/Rule/phpstan-test-provenance-tip-filter.neon'];
	}

	// The function-caused error (on FilterRewriter's rewritten clamp() call, tagged
	// FUNCTION_NO_TIP_ATTRIBUTE) never gets a tip, however macro-bearing its own line is -
	// "Functions: no tip" is unconditional. The macro-caused error (on the plain `true`
	// ConstFetch inside {if true}, never touched by FilterRewriter) still gets the line-map tip
	// listing BOTH macro tags on that shared line, over-attributing cosmetically to {foreach} too
	// - the accepted direction, since the line map cannot pair an error to the specific
	// macro that caused it.
	public function testFunctionNeverTippedButAnUnrelatedNodeOnTheSameMacroLineStillIs(): void
	{
		$this->analyse(
			[self::FixtureFile],
			[
				['clamp call denied.', 1],
				[
					'true constant denied.',
					1,
					'Generated by a macro on this line: {foreach} at column 1, {if} at column 38.',
				],
			],
		);
	}

}
