<?php

/** Generated by Latte 3.0.26 */

use Latte\Runtime as LR;

/** source: fixtures/capture-spaceless.latte */
final class LatteTpl_fixtures_capture_spaceless_latte_520212b0 extends Latte\Runtime\Template
{
	public const Source = 'fixtures/capture-spaceless.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		ob_start(fn() => '') /* line 3 */;
		try {
			echo '	captured ';
			echo LR\Filters::escapeHtmlText($x) /* line 4 */;
			echo "\n";

		} finally {
			$ʟ_tmp = ob_get_length() ? new LR\Html(ob_get_clean()) : ob_get_clean();
		}
		$ʟ_fi = new LR\FilterInfo('html');
		$v = $ʟ_tmp;

		echo "\n";
		ob_start('Latte\Essential\Filters::spacelessHtmlHandler', 4096) /* line 7 */;
		try {
			echo '	<div>
		<span>';
			echo LR\Filters::escapeHtmlText($x) /* line 9 */;
			echo '</span>
	</div>
';

		} finally {
			ob_end_flush();
		}

		echo '
{literal brace}

';
		Tracy\Debugger::barDump($x, '$x') /* line 15 */;
	}
}
