<?php

/** Generated by Latte 3.0.26 */

use Latte\Runtime as LR;

/** source: fixtures/control-flow.latte */
final class LatteTpl_fixtures_control_flow_latte_c4f04f4b extends Latte\Runtime\Template
{
	public const Source = 'fixtures/control-flow.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		if ($show) /* line 7 */ {
			echo '	shown
';
		} elseif ($level > 1) /* line 9 */ {
			echo '	high
';
		} else /* line 11 */ {
			echo '	hidden
';
		}

		echo "\n";
		if (isset($items[0])) /* line 15 */ {
			echo '	first set
';
		}
		echo "\n";
		$ʟ_switch = ($level) /* line 19 */;
		if (in_array($ʟ_switch, [1], true)) /* line 20 */ {
			echo '		one
';
		} elseif (in_array($ʟ_switch, [2, 3], true)) /* line 22 */ {
			echo '		two or three
';
		} else {
			echo '		other
';
		}
		echo "\n";
		$i = 0 /* line 28 */;
		while ($i < 3) /* line 29 */ {
			$i++ /* line 30 */;
		}
		echo "\n";
		for ($j = 0;
		$j < 3;
		$j++) /* line 33 */ {
			echo '	loop ';
			echo LR\Filters::escapeHtmlText($j) /* line 34 */;
			echo "\n";

		}
		echo "\n";
		$ʟ_try[0] = [$ʟ_it ?? null];
		ob_start(fn() => '');
		try /* line 37 */ {
			echo '	risky
';
			if ($flag) /* line 39 */ {
				throw new Latte\Essential\RollbackException;
			}

		} catch (Throwable $ʟ_e) {
			ob_clean();
			if (!($ʟ_e instanceof Latte\Essential\RollbackException) && isset($this->global->coreExceptionHandler)) {
				($this->global->coreExceptionHandler)($ʟ_e, $this);
			}
			echo '	caught
';

		} finally {
			echo ob_get_clean();
			$iterator = $ʟ_it = $ʟ_try[0][0];
		}echo "\n";
		if (($ʟ_loc[1] ?? null) !== ($ʟ_tmp = [$level])) {
			$ʟ_loc[1] = $ʟ_tmp;
			echo '	changed to ';
			echo LR\Filters::escapeHtmlText($level) /* line 45 */;
			echo "\n";

		}

		echo "\n";
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($items, $ʟ_it ?? null) as $item) /* line 48 */ {
			if ($item === null) /* line 49 */ continue;
			if ($item === 'stop') /* line 50 */ break;
			if ($item === 'skip') /* line 51 */ {
				$iterator->skipRound();
				continue;
			}
			echo '	';
			echo LR\Filters::escapeHtmlText($item) /* line 52 */;
			echo "\n";

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo "\n";
		ob_start(fn() => '') /* line 55 */;
		try {
			echo '	captured block
';

		} finally {
			$ʟ_ifA = ob_get_clean();
		}
		if ($showCaptured) /* line 55 */ {
			echo $ʟ_ifA;
		}
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['item' => '48'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
