<?php

/** Generated by Latte 3.0.26 */

use Latte\Runtime as LR;

/** source: fixtures/declarations.latte */
final class LatteTpl_fixtures_declarations_latte_101fb50a extends Latte\Runtime\Template
{
	public const Source = 'fixtures/declarations.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo LR\Filters::escapeHtmlText($label) /* line 9 */;
		echo ' ';
		echo LR\Filters::escapeHtmlText($x) /* line 9 */;
		echo ' ';
		echo LR\Filters::escapeHtmlText($y) /* line 9 */;
		echo ' ';
		echo LR\Filters::escapeHtmlText($z) /* line 9 */;
		echo "\n";
		$flag ??= array_key_exists('flag', get_defined_vars()) ? null : false /* line 10 */;
		if ($flag) /* line 11 */ {
			echo 'on';
		}
		echo "\n";
		echo LR\Filters::escapeHtmlText($late) /* line 13 */;
		echo "\n";
	}


	public function prepare(): array
	{
		extract($this->params);

		$x = 1 /* line 4 */;
		$y = 2 /* line 5 */;
		$z ??= array_key_exists('z', get_defined_vars()) ? null : 3 /* line 6 */;
		$noop = null /* line 7 */;
		$noop = 1 /* line 8 */;
		return get_defined_vars();
	}
}
