<?php

/** Generated by Latte 3.0.26 */

use Latte\Runtime as LR;

/** source: fixtures/filtered-block.latte */
final class LatteTpl_fixtures_filtered_block_latte_7f2fe8d9 extends Latte\Runtime\Template
{
	public const Source = 'fixtures/filtered-block.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		if ($this->hasBlock('title')) /* line 1 */ {
			ob_start(fn() => '') /* line 1 */;
			try {
				(function () {
					extract(func_get_arg(0));
					$this->renderBlock('title', [], 'html') /* line 1 */;
				})(get_defined_vars());
			} finally {
				$ʟ_fi = new LR\FilterInfo('html');
				echo LR\Filters::convertTo($ʟ_fi, 'html', $this->filters->filterContent('trim', $ʟ_fi, $this->filters->filterContent('striptags', $ʟ_fi, ob_get_clean())));
			}
		}
	}
}
