<?php

/** Generated by Latte 3 */

use Latte\Runtime as LR;

/** source: fixtures/foreach-iterator.latte */
final class LatteTpl_fixtures_foreach_iterator_latte_898f2db1 extends Latte\Runtime\Template
{
	public const Source = 'fixtures/foreach-iterator.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		foreach ($items as $item) /* line 4 */ {
			echo '	';
			echo LR\Filters::escapeHtmlText($item) /* line 5 */;
			echo "\n";

		}

		echo "\n";
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($items, $ʟ_it ?? null) as $key => $item) /* line 8 */ {
			echo '	';
			if ($iterator->isFirst()) /* line 9 */ {
				echo 'first ';
			}
			echo LR\Filters::escapeHtmlText($item) /* line 9 */;
			if ($iterator->isLast()) /* line 9 */ {
				echo ' last';
			}
			echo "\n";

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo "\n";
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($groups, $ʟ_it ?? null) as $group) /* line 12 */ {
			foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($group, $ʟ_it ?? null) as $item) /* line 13 */ {
				echo '		';
				if ($iterator->isFirst()) /* line 14 */ {
					echo 'head ';
				}
				echo LR\Filters::escapeHtmlText($item) /* line 14 */;
				if ($iterator->isLast()) /* line 14 */ {
					echo ' tail';
				}
				echo "\n";

			}
			$iterator = $ʟ_it = $ʟ_it->getParent();


		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo "\n";
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($items, $ʟ_it ?? null) as $item) /* line 18 */ {
			do /* line 19 */ {
				echo '		';
				echo LR\Filters::escapeHtmlText($item) /* line 20 */;
				echo "\n";

				if (!$iterator->hasNext() || !($item === $item)) {
					break;
				}
				$iterator->next();
				[, $item] = [$iterator->key(), $iterator->current()];
			}
			while (true);
			echo '	';
			if (!$iterator->isLast()) /* line 22 */ {
				echo ', ';
			}
			echo "\n";

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['item' => '4, 8, 13, 18', 'key' => '8', 'group' => '12'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
