<?php

/** Generated by Latte 3.0.26 */

use Latte\Runtime as LR;

/** source: fixtures/forms-macros.latte */
final class LatteTpl_fixtures_forms_macros_latte_257f81ab extends Latte\Runtime\Template
{
	public const Source = 'fixtures/forms-macros.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$form = $this->global->formsStack[] = $this->global->uiControl['f'] /* line 1 */;
		Nette\Bridges\FormsLatte\Runtime::initializeForm($form);
		echo '<form';
		echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin(end($this->global->formsStack), [], false) /* line 1 */;
		echo '>
	<input';
		echo ($ʟ_elem = Nette\Bridges\FormsLatte\Runtime::item('x', $this->global)->getControlPart())->attributes() /* line 2 */;
		echo '>
	';
		echo ($ʟ_label = Nette\Bridges\FormsLatte\Runtime::item('x', $this->global)->getLabel()) /* line 3 */;
		echo '
	';
		echo LR\Filters::escapeHtmlText(Nette\Bridges\FormsLatte\Runtime::item('x', $this->global)->getError()) /* line 4 */;
		echo "\n";
		echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(end($this->global->formsStack), false) /* line 1 */;
		echo '</form>
';
		array_pop($this->global->formsStack);
		echo "\n";
		$form = $this->global->formsStack[] = $this->global->uiControl['f2'] /* line 7 */;
		Nette\Bridges\FormsLatte\Runtime::initializeForm($form);
		echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form, []) /* line 7 */;
		echo '
	';
		echo Nette\Bridges\FormsLatte\Runtime::item('y', $this->global)->getControl() /* line 8 */;
		echo "\n";
		$this->global->formsStack[] = $formContainer = Nette\Bridges\FormsLatte\Runtime::item('c', $this->global) /* line 9 */;
		echo '		';
		echo Nette\Bridges\FormsLatte\Runtime::item('z', $this->global)->getControl() /* line 10 */;
		echo "\n";
		array_pop($this->global->formsStack);
		$formContainer = end($this->global->formsStack);

		echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack)) /* line 12 */;

		echo "\n";
	}
}
