<?php

/** Generated by Latte 3 */

use Latte\Runtime as LR;

/** source: fixtures/ifcurrent.latte */
final class LatteTpl_fixtures_ifcurrent_latte_90517d0b extends Latte\Runtime\Template
{
	public const Source = 'fixtures/ifcurrent.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		if ($this->global->uiPresenter->isLinkCurrent($dest, mode: 'x')) {
			echo '	';
			echo LR\Filters::escapeHtmlText($label) /* line 5 */;
			echo "\n";
		}
		echo "\n";
		if ($this->global->uiPresenter->getLastCreatedRequestFlag("current")) {
			echo '	';
			echo LR\Filters::escapeHtmlText($label) /* line 9 */;
			echo "\n";
		}
	}
}
