<?php

/** Generated by Latte 3.0.26 */

use Latte\Runtime as LR;

/** source: fixtures/n-attributes.latte */
final class LatteTpl_fixtures_n_attributes_latte_366f42ea extends Latte\Runtime\Template
{
	public const Source = 'fixtures/n-attributes.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		if ($cond) /* line 6 */ {
			echo '<div>shown</div>
';
		}
		echo '
<ul>
';
		foreach ($items as $item) /* line 9 */ {
			echo '	<li>';
			echo LR\Filters::escapeHtmlText($item) /* line 9 */;
			echo '</li>
';

		}

		echo '</ul>

<div>';
		foreach ($items as $item) /* line 12 */ {
			echo LR\Filters::escapeHtmlText($item) /* line 12 */;

		}

		echo '</div>

';
		$ʟ_tag[0] = '';
		if ($cond) /* line 14 */ {
			$ʟ_tag[0] = '</div>' . $ʟ_tag[0];
			echo '<div>';
		}
		echo 'tag-if content';
		echo $ʟ_tag[0];
		echo '

<div';
		echo ($ʟ_tmp = array_filter([$cond ? 'active' : null, $activeClass, 'base'])) ? ' class="' . LR\Filters::escapeHtmlAttr(implode(" ", array_unique($ʟ_tmp))) . '"' : "" /* line 16 */;
		echo '>class</div>

<div';
		echo ($ʟ_tmp = array_filter([$cond ? 'form-group has-error' : 'form-group'])) ? ' class="' . LR\Filters::escapeHtmlAttr(implode(" ", array_unique($ʟ_tmp))) . '"' : "" /* line 18 */;
		echo '>always-truthy class</div>

<div';
		$ʟ_tmp = ['data-x' => $cond ? 1 : null];
		echo Latte\Essential\Nodes\NAttrNode::attrs($ʟ_tmp, false) /* line 20 */;
		echo '></div>

';
		$ʟ_tag[1] = '';
		$ʟ_tmp = LR\HtmlHelpers::validateTagChange($tagName, 'div');
		$ʟ_tag[1] = '</' . $ʟ_tmp . '>' . $ʟ_tag[1];
		echo '<', $ʟ_tmp /* line 22 */;
		echo '>tag';
		echo $ʟ_tag[1];
		echo '

';
		ob_start(fn() => '');
		try {
			echo '<p>';
			ob_start();
			try {
				if ($cond) /* line 24 */ {
					echo 'x';
				}

			} finally {
				$ʟ_ifc[0] = rtrim(ob_get_flush()) === '';
			}
			echo '</p>
';

		} finally {
			if ($ʟ_ifc[0] ?? null) {
				ob_end_clean();

			} else {
				echo ob_get_clean();
			}
		}
		echo '
<script';
		echo $this->global->uiNonce ? " nonce=\"{$this->global->uiNonce}\"" : "";
		echo '>window.x=1;</script>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['item' => '9, 12'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
