<?php

/** Generated by Latte 3 */

use Latte\Runtime as LR;

/** source: fixtures/output-filters.latte */
final class LatteTpl_fixtures_output_filters_latte_903857f4 extends Latte\Runtime\Template
{
	public const Source = 'fixtures/output-filters.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		echo LR\Filters::escapeHtmlText($x) /* line 5 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText(1 + 2) /* line 6 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText(($this->filters->upper)($x)) /* line 7 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText(($this->filters->truncate)($x, 10)) /* line 8 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText(($this->filters->date)($created, 'j.n.Y')) /* line 9 */;
		echo "\n";
		echo $x /* line 10 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText(($this->filters->truncate)(($this->filters->upper)($x), 10)) /* line 11 */;
		echo "\n";
		ob_start(fn() => '') /* line 12 */;
		try {
			echo '	';
			echo LR\Filters::escapeHtmlText($x) /* line 13 */;
			echo "\n";

		} finally {
			$ʟ_tmp = ob_get_length() ? new LR\Html(ob_get_clean()) : ob_get_clean();
		}
		$ʟ_fi = new LR\FilterInfo('html');
		$trimmed = $this->filters->filterContent('trim', $ʟ_fi, $ʟ_tmp);

		echo LR\Filters::escapeHtmlText(($this->filters->translate)('text')) /* line 15 */;
		echo "\n";
		$ʟ_fi = new LR\FilterInfo('html');
		echo LR\Filters::convertTo($ʟ_fi, 'html', $this->filters->filterContent('translate', $ʟ_fi, 'greeting')) /* line 16 */;
		echo "\n";
	}
}
