<?php

/** Generated by Latte 3 */

use Latte\Runtime as LR;

/** source: fixtures/ui-macros.latte */
final class LatteTpl_fixtures_ui_macros_latte_1e9a68ee extends Latte\Runtime\Template
{
	public const Source = 'fixtures/ui-macros.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		$ʟ_tmp = $this->global->uiControl->getComponent('menu');
		if ($ʟ_tmp instanceof Nette\Application\UI\Renderable) $ʟ_tmp->redrawControl(null, false);
		$ʟ_tmp->render() /* line 3 */;

		echo "\n";
		if (!is_object($ʟ_tmp = $obj)) $ʟ_tmp = $this->global->uiControl->getComponent($ʟ_tmp);
		if ($ʟ_tmp instanceof Nette\Application\UI\Renderable) $ʟ_tmp->redrawControl(null, false);
		$ʟ_tmp->renderPart([1, 'a' => 2]) /* line 5 */;

		echo '
<a href="';
		echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('this')) /* line 7 */;
		echo '">this</a>

<a href="';
		echo LR\Filters::escapeHtmlAttr($this->global->uiPresenter->link('Foo:bar')) /* line 9 */;
		echo '">bar</a>

<a href="';
		echo LR\Filters::escapeHtmlAttr($this->global->uiControl->link('Foo:baz', [1, 'x' => 2])) /* line 11 */;
		echo '">baz</a>
';
	}
}
