<?php declare(strict_types = 1);

namespace Tests\OriPhpstan\Nette\Unit\Latte\Postprocess;

use Nette\Utils\FileSystem;
use OriPhpstan\Nette\Latte\Includes\CapturedOverlay;
use OriPhpstan\Nette\Latte\Includes\LatteUniverse;
use OriPhpstan\Nette\Latte\Includes\SiteScopeStore;
use OriPhpstan\Nette\Latte\Includes\TemplateContext;
use OriPhpstan\Nette\Latte\Includes\TemplateEdgeIndex;
use OriPhpstan\Nette\Latte\Postprocess\DeclarationInjector;
use OriPhpstan\Nette\Latte\Postprocess\LineMapper;
use OriPhpstan\Nette\Latte\Version\ShapeFamily;
use PhpParser\PrettyPrinter\Standard;
use PHPStan\Parser\Parser;
use PHPStan\Testing\PHPStanTestCase;
use Tests\OriPhpstan\Nette\Toolkit\BaseTestCase;
use Tests\OriPhpstan\Nette\Toolkit\Latte3\Latte3Layouts;
use Tests\OriPhpstan\Nette\Toolkit\TestAdapter;
use function assert;
use function dirname;
use function substr_count;

// The injector over the committed raw snapshots of every Latte line: the same latteMain /
// latteMain_ctx{i} / block methods come out of the Latte 3 layout (main(array $ʟ_args): void plus
// the head in prepare(): array) as out of Latte 2's, so nothing after the injector knows the line.
final class DeclarationInjectorLayoutTest extends BaseTestCase
{

	private const SNAPSHOT_DIRECTORIES = [
		ShapeFamily::LATTE_2 => 'raw',
		ShapeFamily::LATTE_30 => 'latte3.0/raw',
		ShapeFamily::LATTE_31 => 'latte3.1/raw',
	];

	public function testLatte31HeadMovesInFrontOfTheBodyAndPrepareGoes(): void
	{
		self::assertSame(<<<'PHP'
<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/declarations.latte */
final class LatteTpl_fixtures_declarations_latte_101fb50a extends \Latte\Runtime\Template
{
    /**
     * @var int
     */
    private static $prop_0_y;
    /**
     * @var bool
     */
    private static $prop_1_flag;
    /**
     * @var string
     */
    private static $prop_2_late;
    /**
     * @param string $title
     * @param int|null $count
     * @param array<string> $tags
     * @param array<int, string> $labels
     * @param string $label
     */
    public function latteMain($title, $count, $tags, $labels, $label): void
    {
        $x = 1;
        self::$prop_0_y = 2;
        $y = self::$prop_0_y;
        $z ??= 3;
        $noop = \null;
        $noop = 1;
        echo \Latte\Runtime\HtmlHelpers::escapeText($label);
        echo ' ';
        echo \Latte\Runtime\HtmlHelpers::escapeText($x);
        echo ' ';
        echo \Latte\Runtime\HtmlHelpers::escapeText($y);
        echo ' ';
        echo \Latte\Runtime\HtmlHelpers::escapeText($z);
        echo "\n";
        self::$prop_1_flag = \false;
        $flag ??= self::$prop_1_flag;
        if ($flag) {
            echo 'on';
        }
        echo "\n";
        $late = self::$prop_2_late;
        echo \Latte\Runtime\HtmlHelpers::escapeText($late);
        echo "\n";
    }
}
PHP, $this->inject(ShapeFamily::LATTE_31, 'declarations'));
	}

	public function testLatte30LayoutOnlyDiffersFromLatte31ByItsOwnGeneratedCode(): void
	{
		self::assertSame(<<<'PHP'
<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/declarations.latte */
final class LatteTpl_fixtures_declarations_latte_101fb50a extends \Latte\Runtime\Template
{
    /**
     * @var int
     */
    private static $prop_0_y;
    /**
     * @var bool
     */
    private static $prop_1_flag;
    /**
     * @var string
     */
    private static $prop_2_late;
    public const Source = 'fixtures/declarations.latte';
    /**
     * @param string $title
     * @param int|null $count
     * @param array<string> $tags
     * @param array<int, string> $labels
     * @param string $label
     */
    public function latteMain($title, $count, $tags, $labels, $label): void
    {
        $x = 1;
        self::$prop_0_y = 2;
        $y = self::$prop_0_y;
        $z ??= 3;
        $noop = \null;
        $noop = 1;
        echo \Latte\Runtime\Filters::escapeHtmlText($label);
        echo ' ';
        echo \Latte\Runtime\Filters::escapeHtmlText($x);
        echo ' ';
        echo \Latte\Runtime\Filters::escapeHtmlText($y);
        echo ' ';
        echo \Latte\Runtime\Filters::escapeHtmlText($z);
        echo "\n";
        self::$prop_1_flag = \false;
        $flag ??= self::$prop_1_flag;
        if ($flag) {
            echo 'on';
        }
        echo "\n";
        $late = self::$prop_2_late;
        echo \Latte\Runtime\Filters::escapeHtmlText($late);
        echo "\n";
    }
}
PHP, $this->inject(ShapeFamily::LATTE_30, 'declarations'));
	}

	public function testLatte2LayoutKeepsItsPrepareAndArrayReturn(): void
	{
		self::assertSame(<<<'PHP'
<?php

use Latte\Runtime as LR;
final class LatteTpl_fixtures_declarations_latte_101fb50a extends \Latte\Runtime\Template
{
    /**
     * @var int
     */
    private static $prop_0_y;
    /**
     * @var bool
     */
    private static $prop_1_flag;
    /**
     * @var string
     */
    private static $prop_2_late;
    /**
     * @param string $title
     * @param int|null $count
     * @param array<string> $tags
     * @param array<int, string> $labels
     * @param string $label
     * @return array{}
     */
    public function latteMain($title, $count, $tags, $labels, $label): array
    {
        echo "\n";
        $x = 1;
        self::$prop_0_y = 2;
        $y = self::$prop_0_y;
        $z ??= 3;
        $noop = \null;
        $noop = 1;
        echo \Latte\Runtime\Filters::escapeHtmlText($label);
        echo ' ';
        echo \Latte\Runtime\Filters::escapeHtmlText($x);
        echo ' ';
        echo \Latte\Runtime\Filters::escapeHtmlText($y);
        echo ' ';
        echo \Latte\Runtime\Filters::escapeHtmlText($z);
        echo "\n";
        self::$prop_1_flag = \false;
        $flag ??= self::$prop_1_flag;
        if ($flag) {
            echo 'on';
        }
        echo "\n";
        $late = self::$prop_2_late;
        echo \Latte\Runtime\Filters::escapeHtmlText($late);
        echo "\n";
        return \get_defined_vars();
    }
    /**
     * @param string $title
     * @param int|null $count
     * @param array<string> $tags
     * @param array<int, string> $labels
     * @param string $label
     */
    public function lattePrepare($title, $count, $tags, $labels, $label): void
    {
        \Nette\Bridges\ApplicationLatte\UIRuntime::initialize($this, $this->parentName, $this->blocks);
    }
}
PHP, $this->inject(ShapeFamily::LATTE_2, 'declarations'));
	}

	/**
	 * @dataProvider provideLatte3Lines
	 */
	public function testParametersBecomeMainParamsAndTheParamsOnlyPrepareGoes(string $latteLine): void
	{
		$php = $this->inject($latteLine, 'parameters');

		self::assertStringContainsString(
			"    /**\n     * @param string \$name\n     * @param int \$age\n     */\n"
			. "    public function latteMain(\$name, \$age = 18): void\n    {\n        echo '\nHello ';\n",
			$php,
		);
		self::assertStringNotContainsString('lattePrepare', $php);
		self::assertStringNotContainsString('$this->params', $php);
		self::assertStringNotContainsString("\u{29F}_args", $php);
	}

	/**
	 * @dataProvider provideLatte3Lines
	 */
	public function testBlockMethodsLoseTheirPrologAndTakeTheHeaderParams(string $latteLine): void
	{
		$php = $this->inject($latteLine, 'parameters-blocks');

		self::assertStringContainsString(
			"    /**\n     * @param string \$p\n     */\n    public function latteMain(\$p): void\n    {\n"
			. "        \$this->renderBlock('b', \\get_defined_vars());\n        echo \"\\n\";\n    }\n"
			. "    /**\n     * @param string \$p\n     */\n    public function blockB(\$p): void\n    {\n",
			$php,
		);
		self::assertStringNotContainsString('extract(', $php);
		self::assertStringNotContainsString('lattePrepare', $php);
	}

	/**
	 * @dataProvider provideLatte3Lines
	 */
	public function testTemplateWithoutAHeadHasNoPrepareToAbsorb(string $latteLine): void
	{
		$php = $this->inject($latteLine, 'embed');

		self::assertStringContainsString(
			"    /**\n     * @param string \$mode\n     */\n    public function latteMain(\$mode): void\n    {\n"
			. "        echo \"\\n\";\n        \$this->renderBlock('sub', \\get_defined_vars());\n",
			$php,
		);
		self::assertStringContainsString(
			"    public function blockSub(\$mode): void\n    {\n        echo 'embedded sub block';\n    }\n",
			$php,
		);
		self::assertStringNotContainsString('prepare', $php);
		self::assertStringNotContainsString('snippetDriver?->renderSnippets', $php);
	}

	/**
	 * @dataProvider provideLatte3Lines
	 */
	public function testContextClonesCarryTheHoistedHeadAndNoReturnDoc(string $latteLine): void
	{
		$contexts = [new TemplateContext(['x' => 'int'], []), new TemplateContext(['x' => 'string'], [])];
		$php = $this->inject($latteLine, 'declarations', $contexts);

		self::assertStringNotContainsString('function latteMain(', $php);
		self::assertStringNotContainsString('@return', $php);
		self::assertSame(1, substr_count($php, '@param int $x'));
		self::assertSame(1, substr_count($php, '@param string $x'));
		self::assertSame(
			2,
			substr_count(
				$php,
				"        \$x = 1;\n        self::\$prop_0_y = 2;\n        \$y = self::\$prop_0_y;\n        \$z ??= 3;\n",
			),
		);
		self::assertStringContainsString("    public function latteMain_ctx0(\$x): void\n", $php);
		self::assertStringContainsString("    public function latteMain_ctx1(\$x): void\n", $php);
	}

	public function testLatte2ContextClonesKeepTheReturnDoc(): void
	{
		$contexts = [new TemplateContext(['x' => 'int'], [])];
		$php = $this->inject(ShapeFamily::LATTE_2, 'declarations', $contexts);

		self::assertStringContainsString(
			"    /**\n     * @param int \$x\n     * @return array{}\n     */\n    public function latteMain_ctx0(\$x): array\n",
			$php,
		);
		self::assertStringContainsString('public function lattePrepare($x): void', $php);
	}

	/**
	 * @return iterable<string, array{string}>
	 */
	public function provideLatte3Lines(): iterable
	{
		yield 'latte 3.0' => [ShapeFamily::LATTE_30];
		yield 'latte 3.1' => [ShapeFamily::LATTE_31];
	}

	/**
	 * @param list<TemplateContext> $contexts
	 */
	private function inject(string $latteLine, string $fixture, array $contexts = []): string
	{
		$fixtures = dirname(__DIR__) . '/Fixtures';
		$directory = self::SNAPSHOT_DIRECTORIES[$latteLine] ?? null;
		self::assertNotNull($directory);
		$php = FileSystem::read($fixtures . '/__snapshots__/' . $directory . '/' . $fixture . '.latte.php');
		$source = FileSystem::read($fixtures . '/' . $fixture . '.latte');

		$parser = PHPStanTestCase::getContainer()->getService('currentPhpVersionSimpleParser');
		assert($parser instanceof Parser);
		$stmts = $parser->parseString($php);

		$family = $latteLine === ShapeFamily::LATTE_2
			? new ShapeFamily(ShapeFamily::LATTE_2, ShapeFamily::FORMS_MACROS)
			: Latte3Layouts::family($latteLine);
		$lineMapper = new LineMapper($family->lineMarkerPattern());
		$lineMapper->remap($stmts, $lineMapper->buildMap($php));

		$universe = new LatteUniverse([], '');
		$injector = new DeclarationInjector(
			$parser,
			new TemplateEdgeIndex($universe, TestAdapter::accessor()),
			$universe,
			new CapturedOverlay(new SiteScopeStore('/__absent_sitescope_store__'), true),
		);
		$declarations = TestAdapter::create()->extractFacts(
			$source,
			'fixtures/' . $fixture . '.latte',
		)->getDeclarations();

		self::assertSame([], $injector->inject($stmts, $declarations, $family, $contexts));

		return (new Standard())->prettyPrintFile($stmts);
	}

}
