<?php

declare (strict_types=1);
/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/scoped-foreach.latte */
final class LatteTpl_fixtures_scoped_foreach_latte_8809dd88 extends \Latte\Runtime\Template
{
    /**
     * @param array<int, string> $items
     * @param array<int, array{int, string}> $pairs
     */
    public function latteMain($items, $pairs): void
    {
        foreach ($items as $key => $item) {
            echo '	';
            echo $key;
            echo ': ';
            echo $item;
            echo "\n";
        }
        echo '<ul>
';
        foreach ($items as $item) {
            echo '	<li>';
            echo $item;
            echo '</li>
';
        }
        echo '</ul>
';
        $iterator = new \Latte\Essential\CachingIterator($items);
        foreach ($items as $item) {
            echo '	';
            echo $iterator->counter;
            echo ' ';
            echo $item;
            echo "\n";
        }
        if ($iterator->isEmpty()) {
            echo '	empty
';
        }
        $iterator = new \Latte\Essential\CachingIterator($pairs);
        foreach ($pairs as [$number, $label]) {
            echo '	';
            foreach ($items as $item) {
                echo $number;
                echo $label;
                echo $item;
            }
            echo "\n";
        }
    }
}