<?php declare(strict_types = 1);

namespace OriPhpstan\Nette\Latte\Rule;

use OriPhpstan\Nette\Latte\FixSupport;
use OriPhpstan\Nette\Latte\Includes\TemplateEdgeIndex;
use OriPhpstan\Nette\Latte\Postprocess\FilterRewriter;
use PhpParser\Node;
use PHPStan\Analyser\Scope;
use PHPStan\Rules\FileRuleError;
use PHPStan\Rules\IdentifierRuleError;
use PHPStan\Rules\LineRuleError;
use PHPStan\Rules\MetadataRuleError;
use PHPStan\Rules\NonIgnorableRuleError;
use PHPStan\Rules\Rule;
use PHPStan\Rules\RuleErrorBuilder;
use PHPStan\Rules\TipRuleError;
use function array_map;
use function count;
use function implode;
use function is_string;
use function sprintf;

/**
 * @template TNodeType of Node
 * @implements Rule<TNodeType>
 */
final class LatteProvenanceTipRule implements Rule
{

	/** @var Rule<TNodeType> */
	private Rule $rule;

	private TemplateEdgeIndex $templateEdgeIndex;

	/**
	 * @param Rule<TNodeType> $rule
	 */
	public function __construct(Rule $rule, TemplateEdgeIndex $templateEdgeIndex)
	{
		$this->rule = $rule;
		$this->templateEdgeIndex = $templateEdgeIndex;
	}

	public function getNodeType(): string
	{
		return $this->rule->getNodeType();
	}

	/**
	 * @param TNodeType $node
	 * @return list<IdentifierRuleError>
	 */
	public function processNode(Node $node, Scope $scope): array
	{
		$errors = $this->rule->processNode($node, $scope);

		if ($errors === [] || FixSupport::supportsFixes($scope)) {
			return $errors;
		}

		$tip = $this->provenanceTip($node, $scope);
		if ($tip === null) {
			return $errors;
		}

		// A dump call's own error (identifier orisai.nette.latte.debugDump) is a diagnostic the developer wrote
		// directly, not generated code - decorating it would misattribute it to whatever macro tag
		// happens to share its line (every {do dumpLatteXxx()} call IS itself a `do` macro tag).
		return array_map(
			static fn (IdentifierRuleError $error): IdentifierRuleError => $error->getIdentifier() === LatteDebugDumpRule::IDENTIFIER
				? $error
				: self::appendTip($error, $tip),
			$errors,
		);
	}

	// Filters are node-precise (FilterRewriter tags the exact call node it builds); macros are
	// line-precise (TemplateFactExtractor's tokenization walk has no per-node granularity to
	// offer). A node carrying the filter attribute never also needs the line-macro lookup - a
	// filter-rewritten call node was never itself typed by the developer as a macro tag. The
	// function no-tip marker is checked BEFORE the line-map fallback (not just instead of the
	// filter check): a harvested function called inside another macro's own tag on the same line
	// (e.g. {foreach}{myFn($x)}{/foreach}) would otherwise inherit that macro's line-map tip -
	// "Functions: no tip" is unconditional, so this short-circuits regardless of what
	// else shares the line.
	private function provenanceTip(Node $node, Scope $scope): ?string
	{
		$filterName = $node->getAttribute(FilterRewriter::FILTER_PROVENANCE_ATTRIBUTE);
		if (is_string($filterName)) {
			return sprintf('Generated by the |%s filter.', $filterName);
		}

		if ($node->getAttribute(FilterRewriter::FUNCTION_NO_TIP_ATTRIBUTE) === true) {
			return null;
		}

		$line = $node->getStartLine();
		if ($line < 1) {
			return null;
		}

		$macros = $this->templateEdgeIndex->factsFor($scope->getFile())->getLineMacros()[$line] ?? [];

		return $this->macroTip($macros);
	}

	// The fact-extractor map only tells us WHICH macros produced code on this line, never WHICH
	// ONE produced the specific expression the error is about - pairing error to originating macro
	// tag is not something a line-oriented map can do. Listing every occurrence with its column is
	// the honest degree of precision available; a mixed handwritten+macro line (or several macro
	// tags on one line) over-attributes cosmetically rather than guessing.

	/**
	 * @param list<array{name: string, column: int}> $macros
	 */
	private function macroTip(array $macros): ?string
	{
		if ($macros === []) {
			return null;
		}

		if (count($macros) === 1) {
			return sprintf('Generated by the {%s} macro at column %d.', $macros[0]['name'], $macros[0]['column']);
		}

		$occurrences = implode(', ', array_map(
			static fn (array $macro): string => sprintf('{%s} at column %d', $macro['name'], $macro['column']),
			$macros,
		));

		return sprintf('Generated by a macro on this line: %s.', $occurrences);
	}

	// Mirrors LatteFixStrippingRule::stripFix()'s property-preservation precedent (message,
	// identifier, line, metadata, nonIgnorable, file) - deliberately omits FixableNodeRuleError:
	// this rule only ever runs on .latte scope (the FixSupport guard above), and
	// LatteFixStrippingRegistry already strips every fixNode() payload for that scope before this
	// decorator's own registry wrapping sees the error (see wiring.neon's registry! chain).
	private static function appendTip(IdentifierRuleError $error, string $tip): IdentifierRuleError
	{
		$builder = RuleErrorBuilder::message($error->getMessage())
			->identifier($error->getIdentifier());

		$existingTip = $error instanceof TipRuleError ? $error->getTip() : null;
		$builder->tip($existingTip !== null ? $existingTip . "\n" . $tip : $tip);

		if ($error instanceof LineRuleError) {
			$builder->line($error->getLine());
		}

		if ($error instanceof MetadataRuleError) {
			$builder->metadata($error->getMetadata());
		}

		if ($error instanceof NonIgnorableRuleError) {
			$builder->nonIgnorable();
		}

		if ($error instanceof FileRuleError) {
			$builder->file($error->getFile(), $error->getFileDescription());
		}

		return $builder->build();
	}

}
