<?php declare(strict_types = 1);

namespace Tests\OriPhpstan\Nette\Unit\Latte\Rule;

use OriPhpstan\Nette\Latte\Rule\LatteFixStrippingRule;
use OriPhpstan\Nette\Latte\Rule\LatteProvenanceTipRule;
use PhpParser\Node\Expr\ConstFetch;
use PHPStan\Rules\Rule;
use PHPStan\Testing\RuleTestCase;
use Tests\OriPhpstan\Nette\Toolkit\PipelineFactory;
use Tests\OriPhpstan\Nette\Unit\Latte\Rule\Fixtures\ProvenanceTipFixtureRule;

// Decorator-level coverage (node-attribute provenance only - the macro line-map path is covered
// end to end by LatteProvenanceTipGettextIntegrationTest and unit-tested in isolation by
// TemplateFactExtractorTest). getRule() chains the real LatteFixStrippingRule underneath (mirrors
// wiring.neon's registry! composition: fix-stripping innermost, provenance-tip outermost), so
// every scenario here also exercises that its own contract survives the tip decorator wrapping it.
/**
 * @extends RuleTestCase<LatteProvenanceTipRule<ConstFetch>>
 */
final class LatteProvenanceTipRuleTest extends RuleTestCase
{

	private const LatteFixtureFile = __DIR__ . '/../Fixtures/Rule/provenance-tip-scenarios.latte';

	private const PhpFixtureFile = __DIR__ . '/../Fixtures/Rule/provenance-tip-scenarios.php';

	private const DebugDumpFixtureFile = __DIR__ . '/../Fixtures/Rule/provenance-tip-debug-dump.latte';

	/**
	 * @return LatteProvenanceTipRule<ConstFetch>
	 */
	protected function getRule(): Rule
	{
		return new LatteProvenanceTipRule(
			new LatteFixStrippingRule(new ProvenanceTipFixtureRule()),
			PipelineFactory::createTemplateEdgeIndex(__DIR__ . '/../Fixtures/Rule'),
		);
	}

	/**
	 * @return list<string>
	 */
	public static function getAdditionalConfigFiles(): array
	{
		return [__DIR__ . '/phpstan-test.neon'];
	}

	// true (line 5): filter-attribute tip appended, no existing tip - also carries a fixNode()
	// payload (LatteFixStrippingRule strips it before this decorator ever sees the error; a
	// crash-free analyse() run here is itself proof the .latte-scope stripping still fires
	// correctly under the added wrapping - see FixSupport's own docblock for why an unstripped
	// fixNode payload against .latte-derived source would blow up instead).
	// false (line 6): filter-attribute tip COMBINED with the wrapped rule's own pre-set tip.
	// null (line 7): no attribute, no macro on that line - error passes through with no tip.
	public function testTipsAppliedCombinedOrOmittedOnLatteScope(): void
	{
		$this->analyse(
			[self::LatteFixtureFile],
			[
				['demo filter error.', 5, 'Generated by the |demoFilter filter.'],
				['demo filter error with own tip.', 6, "Existing tip.\nGenerated by the |demoFilter filter."],
				['plain error.', 7],
			],
		);
	}

	// FixSupport gates the decorator entirely on file extension - a genuine .php file (identical
	// fixture content, same node attribute) never gets a PROVENANCE tip appended: line 6 keeps
	// exactly the wrapped rule's own pre-set tip, untouched and uncombined with anything.
	public function testNoProvenanceTipAddedOnPhpScope(): void
	{
		$this->analyse(
			[self::PhpFixtureFile],
			[
				['demo filter error.', 5],
				['demo filter error with own tip.', 6, 'Existing tip.'],
				['plain error.', 7],
			],
		);
	}

	// PHPStan\Analyser\Error (unlike the raw RuleError returned from processNode()) exposes
	// concrete getters for every property regardless of which optional interfaces the original
	// RuleError implemented - the precedent LatteFixStrippingRule::stripFix() itself guards
	// (message, identifier, metadata, nonIgnorable survive the rebuild the tip decorator performs).
	public function testOtherErrorPropertiesSurviveTipAppending(): void
	{
		$errors = $this->gatherAnalyserErrors([self::LatteFixtureFile]);
		self::assertCount(3, $errors);

		$byLine = [];
		foreach ($errors as $error) {
			$line = $error->getLine();
			if ($line === null) {
				self::fail('Expected every fixture error to carry a real line.');
			}

			$byLine[$line] = $error;
		}

		self::assertSame('test.provenanceTipFixture', $byLine[5]->getIdentifier());
		self::assertSame(['demo' => true], $byLine[5]->getMetadata());
		self::assertFalse($byLine[5]->canBeIgnored());
		self::assertSame('Generated by the |demoFilter filter.', $byLine[5]->getTip());
	}

	// A orisaiNette.latte.debugDump-identified error
	// never gets a provenance tip, even carrying the exact same filter-attribute tag that earns one
	// for every other rule - proven on the SAME line as a sibling error that DOES still get tipped,
	// so the exclusion is identifier-scoped, not a blanket regression of the mechanism.
	public function testDebugDumpIdentifiedErrorNeverGetsATipWhileASiblingErrorOnTheSameLineStillDoes(): void
	{
		$this->analyse(
			[self::DebugDumpFixtureFile],
			[
				['demo filter error.', 5, 'Generated by the |demoFilter filter.'],
				['debug dump passthrough error.', 5],
			],
		);
	}

}
