<?php declare(strict_types = 1);

namespace Tests\OriPhpstan\Nette\Unit\Latte\Rule;

use OriPhpstan\Nette\Latte\Rule\LatteProvenanceTipRule;
use PHPStan\Rules\FileRuleError;
use PHPStan\Rules\IdentifierRuleError;
use PHPStan\Rules\RuleErrorBuilder;
use PHPStan\Rules\TipRuleError;
use ReflectionMethod;
use Tests\OriPhpstan\Nette\Toolkit\BaseTestCase;

// Mirrors LatteFixStrippingRuleFileErrorTest: appendTip() is a private static method taking just
// (IdentifierRuleError, string), so it is reflection-invokable directly, with no Scope/Node
// involved at all - the brief lists `file` among the properties appendTip() must preserve, and
// this is the dedicated test for that property the review flagged as missing.
final class LatteProvenanceTipRuleFileErrorTest extends BaseTestCase
{

	public function testFileRuleErrorIsPreservedWhenATipIsAppended(): void
	{
		$originalError = RuleErrorBuilder::message('Test message')
			->identifier('test.fileError')
			->file(__FILE__, 'Test file description')
			->build();

		$reflectionMethod = new ReflectionMethod(LatteProvenanceTipRule::class, 'appendTip');
		$reflectionMethod->setAccessible(true);

		/** @var IdentifierRuleError $tippedError */
		$tippedError = $reflectionMethod->invoke(null, $originalError, 'Generated by the |demoFilter filter.');

		self::assertInstanceOf(IdentifierRuleError::class, $tippedError);
		self::assertSame('Test message', $tippedError->getMessage());
		self::assertSame('test.fileError', $tippedError->getIdentifier());

		self::assertInstanceOf(FileRuleError::class, $tippedError);
		self::assertSame(__FILE__, $tippedError->getFile());
		self::assertSame('Test file description', $tippedError->getFileDescription());

		self::assertInstanceOf(TipRuleError::class, $tippedError);
		self::assertSame('Generated by the |demoFilter filter.', $tippedError->getTip());
	}

}
