<?php

/** Generated by Latte 3 */

use Latte\Runtime as LR;

/** source: fixtures/blocks-snippets.latte */
final class LatteTpl_fixtures_blocks_snippets_latte_6640b14a extends Latte\Runtime\Template
{
	public const Blocks = [
		0 => ['content' => 'blockContent', 'typed' => 'blockTyped'],
		'snippet' => ['s1' => 'blockS1', 's2' => 'blockS2', 'area1' => 'blockArea1', 'inner' => 'blockInner'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
		echo '

';
		$this->renderBlock('content', get_defined_vars(), 'html') /* pos 11:1 */;
		echo "\n";
		$this->renderBlock('typed', ['value'] + [], 'html') /* pos 13:1 */;
		echo '
<div';
		echo ' id="', htmlspecialchars($this->global->snippetDriver->getHtmlId('s1')), '"';
		echo '>';
		$this->renderBlock('s1', [], null, 'snippet') /* pos 15:6 */;
		echo '</div>

';
		echo '<div id="', htmlspecialchars($this->global->snippetDriver->getHtmlId('s2')), '">';
		$this->renderBlock('s2', [], null, 'snippet') /* pos 17:1 */;
		echo '</div>

';
		$this->renderBlock('area1', [], null, 'snippet') /* pos 21:1 */;
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '	block body ';
		echo LR\HtmlHelpers::escapeText($x) /* pos 4:13 */;
		echo "\n";
	}


	/** {define typed, string $p} on line 7 */
	public function blockTyped(array $ʟ_args): void
	{
		extract($this->params);
		$p = $ʟ_args[0] ?? $ʟ_args['p'] ?? null;
		unset($ʟ_args);

		echo '	typed body ';
		echo LR\HtmlHelpers::escapeText($p) /* pos 8:13 */;
		echo "\n";
	}


	/** n:snippet="s1" on line 15 */
	public function blockS1(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->global->snippetDriver->enter('s1', 'static') /* pos 15:6 */;
		try {
			echo 'snippet content';

		} finally {
			$this->global->snippetDriver->leave();
		}
	}


	/** {snippet s2} on line 17 */
	public function blockS2(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->global->snippetDriver->enter('s2', 'static') /* pos 17:1 */;
		try {
			echo '
	explicit snippet
';

		} finally {
			$this->global->snippetDriver->leave();
		}
	}


	/** {snippetArea area1} on line 21 */
	public function blockArea1(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->global->snippetDriver->enter('area1', 'area');
		try {
			echo '	';
			echo '<div id="', htmlspecialchars($this->global->snippetDriver->getHtmlId('inner')), '">';
			$this->renderBlock('inner', [], null, 'snippet') /* pos 22:2 */;
			echo '</div>
';

		} finally {
			$this->global->snippetDriver->leave();
		}
	}


	/** {snippet inner} on line 22 */
	public function blockInner(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->global->snippetDriver->enter('inner', 'static') /* pos 22:2 */;
		try {
			echo 'area snippet';

		} finally {
			$this->global->snippetDriver->leave();
		}
	}
}
