<?php declare(strict_types=1);

/** Generated by Latte 3.1.6 */

use Latte\Runtime as LR;

/** source: fixtures/capture-spaceless.latte */
final class LatteTpl_fixtures_capture_spaceless_latte_520212b0 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		ob_start(fn() => '') /* pos 3:1 */;
		try {
			echo '	captured ';
			echo LR\HtmlHelpers::escapeText($x) /* pos 4:11 */;
			echo "\n";

		} finally {
			$ʟ_tmp = ob_get_length() ? new LR\Html(ob_get_clean()) : ob_get_clean();
		}
		$ʟ_fi = new LR\FilterInfo('html');
		$v = $ʟ_tmp;

		echo "\n";
		Latte\Essential\WhitespaceMinifier::start('html') /* pos 7:1 */;
		try {
			echo '	<div>
		<span>';
			echo LR\HtmlHelpers::escapeText($x) /* pos 9:9 */;
			echo '</span>
	</div>
';

		} finally {
			Latte\Essential\WhitespaceMinifier::end();
		}

		echo '
{literal brace}

';
		Tracy\Debugger::barDump($x, '$x') /* pos 15:1 */;
	}
}
