<?php declare(strict_types=1);

/** Generated by Latte 3.1.6 */

use Latte\Runtime as LR;

/** source: fixtures/control-flow.latte */
final class LatteTpl_fixtures_control_flow_latte_c4f04f4b extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		if ($show) /* pos 7:1 */ {
			echo '	shown
';
		} elseif ($level > 1) /* pos 9:1 */ {
			echo '	high
';
		} else /* pos 11:1 */ {
			echo '	hidden
';
		}

		echo "\n";
		if (isset($items[0])) /* pos 15:1 */ {
			echo '	first set
';
		}
		echo "\n";
		$ʟ_switch = ($level) /* pos 19:1 */;
		if ($ʟ_switch === (1)) /* pos 20:2 */ {
			echo '		one
';
		} elseif (in_array($ʟ_switch, [2, 3], true)) /* pos 22:2 */ {
			echo '		two or three
';
		} else {
			echo '		other
';
		}
		echo "\n";
		$i = 0 /* pos 28:1 */;
		while ($i < 3) /* pos 29:1 */ {
			$i++ /* pos 30:2 */;
		}
		echo "\n";
		for ($j = 0;
		$j < 3;
		$j++) /* pos 33:1 */ {
			echo '	loop ';
			echo LR\HtmlHelpers::escapeText($j) /* pos 34:7 */;
			echo "\n";

		}
		echo "\n";
		$ʟ_try[0] = [$ʟ_it ?? null];
		ob_start(fn() => '');
		try /* pos 37:1 */ {
			echo '	risky
';
			if ($flag) /* pos 39:2 */ {
				throw new Latte\Essential\RollbackException;
			}

		} catch (Throwable $ʟ_e) {
			ob_clean();
			if (!($ʟ_e instanceof Latte\Essential\RollbackException) && isset($this->global->coreExceptionHandler)) {
				($this->global->coreExceptionHandler)($ʟ_e, $this);
			}
			echo '	caught
';

		} finally {
			echo ob_get_clean();
			$iterator = $ʟ_it = $ʟ_try[0][0];
		}echo "\n";
		if (($ʟ_loc[1] ?? null) !== ($ʟ_tmp = [$level])) {
			$ʟ_loc[1] = $ʟ_tmp;
			echo '	changed to ';
			echo LR\HtmlHelpers::escapeText($level) /* pos 45:13 */;
			echo "\n";

		}

		echo "\n";
		foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($items, $ʟ_it ?? null) as $item) /* pos 48:1 */ {
			if ($item === null) /* pos 49:2 */ continue;
			if ($item === 'stop') /* pos 50:2 */ break;
			if ($item === 'skip') /* pos 51:2 */ {
				$iterator->skipRound();
				continue;
			}
			echo '	';
			echo LR\HtmlHelpers::escapeText($item) /* pos 52:2 */;
			echo "\n";

		}
		$iterator = $ʟ_it = $ʟ_it->getParent();

		echo "\n";
		ob_start(fn() => '') /* pos 55:1 */;
		try {
			echo '	captured block
';

		} finally {
			$ʟ_ifA = ob_get_clean();
		}
		if ($showCaptured) /* pos 55:1 */ {
			echo $ʟ_ifA;
		}
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['item' => '48'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
