<?php

/** Generated by Latte 3 */

use Latte\Runtime as LR;

/** source: fixtures/declarations.latte */
final class LatteTpl_fixtures_declarations_latte_101fb50a extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo LR\HtmlHelpers::escapeText($label) /* pos 9:1 */;
		echo ' ';
		echo LR\HtmlHelpers::escapeText($x) /* pos 9:10 */;
		echo ' ';
		echo LR\HtmlHelpers::escapeText($y) /* pos 9:15 */;
		echo ' ';
		echo LR\HtmlHelpers::escapeText($z) /* pos 9:20 */;
		echo "\n";
		$flag ??= array_key_exists('flag', get_defined_vars()) ? null : false /* pos 10:1 */;
		if ($flag) /* pos 11:1 */ {
			echo 'on';
		}
		echo "\n";
		echo LR\HtmlHelpers::escapeText($late) /* pos 13:1 */;
		echo "\n";
	}


	public function prepare(): array
	{
		extract($this->params);

		$x = 1 /* pos 4:1 */;
		$y = 2 /* pos 5:1 */;
		$z ??= array_key_exists('z', get_defined_vars()) ? null : 3 /* pos 6:1 */;
		$noop = null /* pos 7:1 */;
		$noop = 1 /* pos 8:1 */;
		return get_defined_vars();
	}
}
