<?php declare(strict_types=1);

/** Generated by Latte 3.1.6 */

use Latte\Runtime as LR;

/** source: fixtures/embed.latte */
final class LatteTpl_fixtures_embed_latte_1475771c extends Latte\Runtime\Template
{
	public const Blocks = [
		['sub' => 'blockSub'],
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		$this->renderBlock('sub', get_defined_vars()) /* pos 3:1 */;
		echo '

';
		$this->enterBlockLayer(1, get_defined_vars()) /* pos 5:1 */;
		try {
			$this->createTemplate('blocks-snippets.latte', ['mode' => $mode], "embed")->renderToContentType('html') /* pos 5:1 */;
		} finally {
			$this->leaveBlockLayer();
		}
		echo "\n";
		$this->enterBlockLayer(2, get_defined_vars()) /* pos 11:1 */;
		$this->copyBlockLayer();
		try {
			$this->renderBlock('sub', [], 'html') /* pos 11:1 */;
		} finally {
			$this->leaveBlockLayer();
		}
	}


	/** {block sub} on line 3 */
	public function blockSub(array $ʟ_args): void
	{
		echo 'embedded sub block';
	}


	/** {block content} on line 6 */
	public function blockContent(array $ʟ_args): void
	{
		extract(end($this->varStack));
		extract($ʟ_args);
		unset($ʟ_args);

		echo '		override content ';
		echo LR\HtmlHelpers::escapeText($mode) /* pos 7:20 */;
		echo "\n";
	}
}
