<?php

/** Generated by Latte 3 */

use Latte\Runtime as LR;

/** source: fixtures/extends.latte */
final class LatteTpl_fixtures_extends_latte_4e7b036e extends Latte\Runtime\Template
{
	public const Blocks = [
		['title' => 'blockTitle'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		$this->renderBlock('title', get_defined_vars()) /* pos 4:1 */;
		echo "\n";
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = 'parent.latte';
		return get_defined_vars();
	}


	/** {block title} on line 4 */
	public function blockTitle(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText($title) /* pos 4:14 */;
	}
}
