<?php declare(strict_types=1);

/** Generated by Latte 3.1.6 */

use Latte\Runtime as LR;

/** source: fixtures/forms-macros.latte */
final class LatteTpl_fixtures_forms_macros_latte_257f81ab extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->global->forms->begin($form = $this->global->uiControl['f'], global: $this->global) /* pos 1:7 */;
		echo '<form';
		echo $this->global->forms->renderFormBegin([], false) /* pos 1:7 */;
		echo '>
	<input';
		echo ($ʟ_elem = $this->global->forms->get('x')->getControlPart())->attributes() /* pos 2:9 */;
		echo '>
	';
		echo ($ʟ_label = $this->global->forms->get('x')->getLabel()) /* pos 3:2 */;
		echo '
	';
		echo LR\HtmlHelpers::escapeText($this->global->forms->get('x')->getError()) /* pos 4:2 */;
		echo "\n";
		echo $this->global->forms->renderFormEnd(false) /* pos 1:7 */;
		echo '</form>
';
		$this->global->forms->end();
		echo "\n";
		$this->global->forms->begin($form = $this->global->uiControl['f2'], global: $this->global) /* pos 7:1 */;
		echo $this->global->forms->renderFormBegin([]) /* pos 7:1 */;
		echo '
	';
		echo $this->global->forms->get('y')->getControl() /* pos 8:2 */;
		echo "\n";
		$this->global->forms->begin($formContainer = $this->global->forms->get('c', Nette\Forms\Container::class)) /* pos 9:2 */;
		echo '		';
		echo $this->global->forms->get('z')->getControl() /* pos 10:3 */;
		echo "\n";

		$this->global->forms->end();
		$formContainer = $this->global->forms->getScope();
		echo $this->global->forms->renderFormEnd() /* pos 12:1 */;
		$this->global->forms->end();

		echo "\n";
	}
}
