<?php

/** Generated by Latte 3 */

use Latte\Runtime as LR;

/** source: fixtures/layout.latte */
final class LatteTpl_fixtures_layout_latte_c2b2d2f9 extends Latte\Runtime\Template
{
	public const Blocks = [
		['title' => 'blockTitle', 'content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		$this->renderBlock('title', get_defined_vars()) /* pos 7:1 */;
		echo '

';
		$this->renderBlock('content', get_defined_vars()) /* pos 9:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = 'parent.latte';
		$this->createTemplate('blocks-snippets.latte', $this->params, "import")->render() /* pos 3:1 */;
		$subtitle = 'sub' /* pos 5:1 */;
		return get_defined_vars();
	}


	/** {block title} on line 7 */
	public function blockTitle(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText($title) /* pos 7:14 */;
		echo ' ';
		echo LR\HtmlHelpers::escapeText($subtitle) /* pos 7:23 */;
	}


	/** {block content} on line 9 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('typed', ['value'] + [], 'html') /* pos 10:2 */;
	}
}
