<?php

/** Generated by Latte 3 */

use Latte\Runtime as LR;

/** source: fixtures/n-attributes.latte */
final class LatteTpl_fixtures_n_attributes_latte_366f42ea extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		if ($cond) /* pos 6:6 */ {
			echo '<div>shown</div>
';
		}
		echo '
<ul>
';
		foreach ($items as $item) /* pos 9:6 */ {
			echo '	<li>';
			echo LR\HtmlHelpers::escapeText($item) /* pos 9:34 */;
			echo '</li>
';

		}

		echo '</ul>

<div>';
		foreach ($items as $item) /* pos 12:6 */ {
			echo LR\HtmlHelpers::escapeText($item) /* pos 12:40 */;

		}

		echo '</div>

';
		$ʟ_tag = '';
		if ($cond) /* pos 14:6 */ {
			$ʟ_tag = '</div>' . $ʟ_tag;
			echo '<div>';
		}
		$ʟ_tags[0] = $ʟ_tag;
		echo 'tag-if content';
		echo $ʟ_tags[0];
		echo '

<div';
		echo ($ʟ_tmp = array_filter([$cond ? 'active' : null, $activeClass, 'base'])) ? ' class="' . LR\HtmlHelpers::escapeAttr(implode(" ", array_unique($ʟ_tmp))) . '"' : "" /* pos 16:6 */;
		echo '>class</div>

<div';
		echo ($ʟ_tmp = array_filter([$cond ? 'form-group has-error' : 'form-group'])) ? ' class="' . LR\HtmlHelpers::escapeAttr(implode(" ", array_unique($ʟ_tmp))) . '"' : "" /* pos 18:6 */;
		echo '>always-truthy class</div>

<div';
		$ʟ_tmp = ['data-x' => $cond ? 1 : null];
		echo Latte\Essential\Nodes\NAttrNode::attrs($ʟ_tmp, false) /* pos 20:6 */;
		echo '></div>

';
		$ʟ_tag = '';
		$ʟ_tmp = LR\HtmlHelpers::validateTagChange($tagName, 'div');
		$ʟ_tag = '</' . $ʟ_tmp . '>' . $ʟ_tag;
		echo '<', $ʟ_tmp /* pos 22:1 */;
		echo '>';
		$ʟ_tags[1] = $ʟ_tag;
		echo 'tag';
		echo $ʟ_tags[1];
		echo '

';
		ob_start(fn() => '');
		try {
			echo '<p>';
			ob_start();
			try {
				if ($cond) /* pos 24:16 */ {
					echo 'x';
				}

			} finally {
				$ʟ_ifc[0] = rtrim(ob_get_flush()) === '';
			}
			echo '</p>
';

		} finally {
			if ($ʟ_ifc[0] ?? null) {
				ob_end_clean();

			} else {
				echo ob_get_clean();
			}
		}
		echo '
<script';
		echo $this->global->uiNonce ? " nonce=\"{$this->global->uiNonce}\"" : "";
		echo '>window.x=1;</script>
';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['item' => '9, 12'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
