<?php declare(strict_types=1);

/** Generated by Latte 3.1.6 */

use Latte\Runtime as LR;

/** source: fixtures/output-filters.latte */
final class LatteTpl_fixtures_output_filters_latte_903857f4 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		echo LR\HtmlHelpers::escapeText($x) /* pos 5:1 */;
		echo "\n";
		echo LR\HtmlHelpers::escapeText(1 + 2) /* pos 6:1 */;
		echo "\n";
		echo LR\HtmlHelpers::escapeText(($this->filters->upper)($x)) /* pos 7:1 */;
		echo "\n";
		echo LR\HtmlHelpers::escapeText(($this->filters->truncate)($x, 10)) /* pos 8:1 */;
		echo "\n";
		echo LR\HtmlHelpers::escapeText(($this->filters->date)($created, 'j.n.Y')) /* pos 9:1 */;
		echo "\n";
		echo $x /* pos 10:1 */;
		echo "\n";
		echo LR\HtmlHelpers::escapeText(($this->filters->truncate)(($this->filters->upper)($x), 10)) /* pos 11:1 */;
		echo "\n";
		ob_start(fn() => '') /* pos 12:1 */;
		try {
			echo '	';
			echo LR\HtmlHelpers::escapeText($x) /* pos 13:2 */;
			echo "\n";

		} finally {
			$ʟ_tmp = ob_get_length() ? new LR\Html(ob_get_clean()) : ob_get_clean();
		}
		$ʟ_fi = new LR\FilterInfo('html');
		$trimmed = $this->filters->filterContent('trim', $ʟ_fi, $ʟ_tmp);
		if ($ʟ_fi->contentType === 'html' && $trimmed !== '') $trimmed = new LR\Html($trimmed);

		echo LR\HtmlHelpers::escapeText(($this->filters->translate)('text')) /* pos 15:1 */;
		echo "\n";
		$ʟ_fi = new LR\FilterInfo('html');
		echo LR\Helpers::convertTo($ʟ_fi, 'html', $this->filters->filterContent('translate', $ʟ_fi, 'greeting')) /* pos 16:1 */;
		echo "\n";
	}
}
