<?php

/** Generated by Latte 3 */

use Latte\Runtime as LR;

/** source: fixtures/parameters-blocks.latte */
final class LatteTpl_fixtures_parameters_blocks_latte_3e63c928 extends Latte\Runtime\Template
{
	public const Blocks = [
		['b' => 'blockB'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		$this->renderBlock('b', get_defined_vars()) /* pos 2:1 */;
		echo "\n";
	}


	public function prepare(): array
	{
		$p = $this->params[0] ?? $this->params['p'] ?? null;
		unset($ʟ_args);

		return get_defined_vars();
	}


	/** {block b} on line 2 */
	public function blockB(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo LR\HtmlHelpers::escapeText($p) /* pos 2:10 */;
	}
}
