<?php

/** Generated by Latte 3 */

use Latte\Runtime as LR;

/** source: fixtures/parameters.latte */
final class LatteTpl_fixtures_parameters_latte_031c1534 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo '
Hello ';
		echo LR\HtmlHelpers::escapeText($name) /* pos 3:7 */;
		echo ', age ';
		echo LR\HtmlHelpers::escapeText($age) /* pos 3:20 */;
		echo "\n";
	}


	public function prepare(): array
	{
		$name = $this->params[0] ?? $this->params['name'] ?? null;
		$age = $this->params[1] ?? $this->params['age'] ?? 18;
		unset($ʟ_args);

		return get_defined_vars();
	}
}
