<?php

/** Generated by Latte 3 */

use Latte\Runtime as LR;

/** source: fixtures/probes.latte */
final class LatteTpl_fixtures_probes_latte_4c7d2b2d extends Latte\Runtime\Template
{
	public const Blocks = [
		['wrapper' => 'blockWrapper'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		echo "\n";
		$this->addBlock($ʟ_nm = (LR\Helpers::stringOrNull($ʟ_tmp = $name) ?? throw new InvalidArgumentException(sprintf('Block name must be a string, %s given.', get_debug_type($ʟ_tmp)))), 'html', [$this->blockName(...)], 0);
		$this->renderBlock($ʟ_nm, get_defined_vars());
		echo '

';
		$this->renderBlock('wrapper', get_defined_vars()) /* pos 7:1 */;
		echo "\n";
		ob_start(fn() => '') /* pos 11:1 */;
		try {
			(function () {
				extract(func_get_arg(0));
				echo 'anonymous filtered ';
				echo LR\HtmlHelpers::escapeText($mode) /* pos 11:34 */;

			})(get_defined_vars());
		} finally {
			$ʟ_fi = new LR\FilterInfo('html');
			echo LR\Helpers::convertTo($ʟ_fi, 'html', $this->filters->filterContent('upper', $ʟ_fi, ob_get_clean()));
		}
		echo '

';
		ob_start(fn() => '');
		try {
			$this->createTemplate('declarations.latte', ['flag' => true], 'sandbox')->renderToContentType('html') /* pos 13:1 */;
		} catch (\Throwable $ʟ_e) {
			if (isset($this->global->coreExceptionHandler)) {
				ob_clean();
				($this->global->coreExceptionHandler)($ʟ_e, $this);
			} else {
				throw $ʟ_e;
			}
		} finally {
			echo ob_get_clean();
		}

		echo "\n";
		Nette\Forms\Blueprint::latte(is_object($ʟ_tmp = 'myForm') ? $ʟ_tmp : $this->global->uiControl[$ʟ_tmp]) /* pos 15:1 */;
		exit;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->createTemplate('blocks-snippets.latte', $this->params, "import")->render() /* pos 1:1 */;
		return get_defined_vars();
	}


	/** {block $name} on line 5 */
	public function blockName(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo 'dynamic ';
		echo LR\HtmlHelpers::escapeText($name) /* pos 5:22 */;
	}


	/** {block wrapper} on line 7 */
	public function blockWrapper(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderParentBlock('wrapper', get_defined_vars()) /* pos 8:2 */;
	}
}
