<?php declare(strict_types=1);

/** Generated by Latte 3 */

use Latte\Runtime as LR;

/** source: fixtures/scoped-foreach.latte */
final class LatteTpl_fixtures_scoped_foreach_latte_8809dd88 extends Latte\Runtime\Template
{

	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		if ($this->global->snippetDriver?->renderSnippets($this->blocks[self::LayerSnippet], $this->params)) {
			return;
		}

		try {
			$ʟ_fe_0 = get_defined_vars();
			unset($key, $item);

			foreach ($items as $key => $item) /* pos 3:1 */ {
				echo '	';
				echo LR\HtmlHelpers::escapeText($key) /* pos 4:2 */;
				echo ': ';
				echo LR\HtmlHelpers::escapeText($item) /* pos 4:10 */;
				echo "\n";

			}

		} finally {
			unset($key, $item);
			if (array_key_exists('key', $ʟ_fe_0)) {
				$key = &$ʟ_fe_0['key'];
			}
			if (array_key_exists('item', $ʟ_fe_0)) {
				$item = &$ʟ_fe_0['item'];
			}

			unset($ʟ_fe_0);
		}

		echo '<ul>
';
		try {
			$ʟ_fe_1 = get_defined_vars();
			unset($item);

			foreach ($items as $item) /* pos 7:6 */ {
				echo '	<li>';
				echo LR\HtmlHelpers::escapeText($item) /* pos 7:34 */;
				echo '</li>
';

			}

		} finally {
			unset($item);
			if (array_key_exists('item', $ʟ_fe_1)) {
				$item = &$ʟ_fe_1['item'];
			}

			unset($ʟ_fe_1);
		}

		echo '</ul>
';
		try {
			$ʟ_fe_2 = get_defined_vars();
			unset($item);

			foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($items, $ʟ_it ?? null) as $item) /* pos 9:1 */ {
				echo '	';
				echo LR\HtmlHelpers::escapeText($iterator->counter) /* pos 10:2 */;
				echo ' ';
				echo LR\HtmlHelpers::escapeText($item) /* pos 10:23 */;
				echo "\n";

			}
			if ($iterator->isEmpty()) /* pos 11:1 */ {
				echo '	empty
';

			}
			$iterator = $ʟ_it = $ʟ_it->getParent();

		} finally {
			unset($item);
			if (array_key_exists('item', $ʟ_fe_2)) {
				$item = &$ʟ_fe_2['item'];
			}

			unset($ʟ_fe_2);
		}

		try {
			$ʟ_fe_4 = get_defined_vars();
			unset($number, $label);

			foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($pairs, $ʟ_it ?? null) as [$number, $label]) /* pos 14:1 */ {
				echo '	';
				try {
					$ʟ_fe_3 = get_defined_vars();
					unset($item);

					foreach ($items as $item) /* pos 15:2 */ {
						echo LR\HtmlHelpers::escapeText($number) /* pos 15:27 */;
						echo LR\HtmlHelpers::escapeText($label) /* pos 15:36 */;
						echo LR\HtmlHelpers::escapeText($item) /* pos 15:44 */;

					}

				} finally {
					unset($item);
					if (array_key_exists('item', $ʟ_fe_3)) {
						$item = &$ʟ_fe_3['item'];
					}

					unset($ʟ_fe_3);
				}

				echo "\n";

			}
			$iterator = $ʟ_it = $ʟ_it->getParent();

		} finally {
			unset($number, $label);
			if (array_key_exists('number', $ʟ_fe_4)) {
				$number = &$ʟ_fe_4['number'];
			}
			if (array_key_exists('label', $ʟ_fe_4)) {
				$label = &$ʟ_fe_4['label'];
			}

			unset($ʟ_fe_4);
		}
	}
}
