<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/blocks-snippets.latte */
final class LatteTpl_fixtures_blocks_snippets_latte_6640b14a extends \Latte\Runtime\Template
{
    public const Blocks = [0 => ['content' => 'blockContent', 'typed' => 'blockTyped'], 'snippet' => ['s1' => 'blockS1', 's2' => 'blockS2', 'area1' => 'blockArea1', 'inner' => 'blockInner']];
    /**
     * @param string $x
     */
    public function latteMain($x): void
    {
        echo "\n";
        $this->blockContent($x);
        echo '

';
        $this->blockContent($x);
        echo "\n";
        $this->blockTyped($x, 'value');
        echo '
<div';
        echo ' id="', \htmlspecialchars(\OriPhpstan\Nette\Latte\Runtime\Helpers::snippetId('s1')), '"';
        echo '>';
        $this->blockS1($x);
        echo '</div>

';
        echo '<div id="', \htmlspecialchars(\OriPhpstan\Nette\Latte\Runtime\Helpers::snippetId('s2')), '">';
        $this->blockS2($x);
        echo '</div>

';
        $this->blockArea1($x);
    }
    /**
     * @param string $x
     */
    public function blockContent($x): void
    {
        echo '	block body ';
        echo $x;
        echo "\n";
    }
    /**
     * @param string $x
     * @param string $p
     */
    public function blockTyped($x, $p): void
    {
        echo '	typed body ';
        echo $p;
        echo "\n";
    }
    /**
     * @param string $x
     */
    public function blockS1($x): void
    {
        echo 'snippet content';
    }
    /**
     * @param string $x
     */
    public function blockS2($x): void
    {
        echo '
	explicit snippet
';
    }
    /**
     * @param string $x
     */
    public function blockArea1($x): void
    {
        echo '	';
        echo '<div id="', \htmlspecialchars(\OriPhpstan\Nette\Latte\Runtime\Helpers::snippetId('inner')), '">';
        $this->blockInner($x);
        echo '</div>
';
    }
    /**
     * @param string $x
     */
    public function blockInner($x): void
    {
        echo 'area snippet';
    }
}