<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/embed.latte */
final class LatteTpl_fixtures_embed_latte_1475771c extends \Latte\Runtime\Template
{
    public const Blocks = [['sub' => 'blockSub'], ['content' => 'blockContent']];
    /**
     * @param string $mode
     */
    public function latteMain($mode): void
    {
        echo "\n";
        $this->blockSub($mode);
        echo '

';
        \OriPhpstan\Nette\Latte\Runtime\Helpers::analyzed(['mode' => $mode]);
        \OriPhpstan\Nette\Latte\Runtime\Helpers::embedTemplate('blocks-snippets.latte');
        echo "\n";
        $this->blockSub($mode);
    }
    /**
     * @param string $mode
     */
    public function blockSub($mode): void
    {
        echo 'embedded sub block';
    }
    /**
     * @param string $mode
     */
    public function blockContent($mode): void
    {
        echo '		override content ';
        echo $mode;
        echo "\n";
    }
}