<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/extends.latte */
final class LatteTpl_fixtures_extends_latte_4e7b036e extends \Latte\Runtime\Template
{
    public const Blocks = [['title' => 'blockTitle']];
    /**
     * @param string $title
     */
    public function latteMain($title): void
    {
        $this->parentName = 'parent.latte';
        echo "\n";
        $this->blockTitle($title);
        echo "\n";
    }
    /**
     * @param string $title
     */
    public function blockTitle($title): void
    {
        echo $title;
    }
}