<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/layout.latte */
final class LatteTpl_fixtures_layout_latte_c2b2d2f9 extends \Latte\Runtime\Template
{
    public const Blocks = [['title' => 'blockTitle', 'content' => 'blockContent']];
    /**
     * @param string $title
     */
    public function latteMain($title): void
    {
        $this->parentName = 'parent.latte';
        $this->createTemplate('blocks-snippets.latte', $this->params, "import")->render();
        $subtitle = 'sub';
        echo "\n";
        $this->blockTitle($title);
        echo '

';
        $this->blockContent($title);
    }
    /**
     * @param string $title
     */
    public function blockTitle($title): void
    {
        echo $title;
        echo ' ';
        echo $subtitle;
    }
    /**
     * @param string $title
     */
    public function blockContent($title): void
    {
        $this->renderBlock('typed', ['value'] + [], 'html');
    }
}