<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/output-filters.latte */
final class LatteTpl_fixtures_output_filters_latte_903857f4 extends \Latte\Runtime\Template
{
    /**
     * @param string $x
     * @param string $name
     * @param \DateTimeImmutable $created
     */
    public function latteMain($x, $name, $created): void
    {
        echo "\n";
        echo $x;
        echo "\n";
        echo 1 + 2;
        echo "\n";
        echo \Latte\Essential\Filters::upper($x);
        echo "\n";
        echo \Latte\Essential\Filters::truncate($x, 10);
        echo "\n";
        echo \Latte\Essential\Filters::date($created, 'j.n.Y');
        echo "\n";
        echo $x;
        echo "\n";
        echo \Latte\Essential\Filters::truncate(\Latte\Essential\Filters::upper($x), 10);
        echo "\n";
        echo '	';
        echo $x;
        echo "\n";
        $trimmed = \Latte\Essential\Filters::trim(\OriPhpstan\Nette\Latte\Runtime\Helpers::filterInfo(), \OriPhpstan\Nette\Latte\Runtime\Helpers::capturedString());
        echo \OriPhpstan\Nette\Latte\Runtime\Helpers::translate('text');
        echo "\n";
        echo \Latte\Runtime\Helpers::convertTo(\OriPhpstan\Nette\Latte\Runtime\Helpers::filterInfo(), 'html', \OriPhpstan\Nette\Latte\Runtime\Helpers::translate('greeting'));
        echo "\n";
    }
}