<?php

/** Generated by Latte 3 */
use Latte\Runtime as LR;
/** source: fixtures/parameters-blocks.latte */
final class LatteTpl_fixtures_parameters_blocks_latte_3e63c928 extends \Latte\Runtime\Template
{
    public const Blocks = [['b' => 'blockB']];
    /**
     * @param string $p
     */
    public function latteMain($p): void
    {
        $this->blockB($p);
        echo "\n";
    }
    /**
     * @param string $p
     */
    public function blockB($p): void
    {
        echo $p;
    }
}